### ISSUE TITLE
Support/Eg for Other Providers

### ISSUE THREAD

**Issue by wahmedswl** [pulumi/pulumi-policy-opa#11]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

Hi, current eg only describe to use OPA with k8s so wanted to know if it only applies to k8s or its generic? If it works with all providers so eg would be awesome!

Thanks

**Comment by leezen** [comment]
Yes, the support is generic across all providers and not specific to kubernetes
