### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by lkt82** [pulumi/pulumi-policy-opa#8]
Hi

I get an error when I try to install the plugin

error: [analyzer plugin policy-opa-0.0.2] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-analyzer-policy-opa-v0.0.2-windows-amd64.tar.gz

## Steps to reproduce

1. Run "pulumi plugin install analyzer policy-opa v0.0.2" on a windows box

Expected: The plugin is installed
Actual: Installation fails

**Comment by emiliza** [comment]
Looks like we've got the url set there, it should be downloading from https://get.pulumi.com/releases/plugins/pulumi-analyzer-policy-opa.exe-v0.0.2-windows-amd64.tar.gz
